### ISSUE TITLE
Ubuntu versions 16.04 onwards doesn't use Upstart

### ISSUE THREAD

**Issue by richietheg** [NeilBetham/livewire-streamer#3]
As Ubuntu have dropped using 'Upstart' and moved to 'systemd', the code given to start the process does not work.

Unfortunately, I am not all that well versed in either system to be able to fix it myself!

**Comment by NeilBetham** [comment]
Ahh, yeah, i'll add a systemd unit file alongside the upstart one.

**Comment by NeilBetham** [comment]
Okay, i've added a new systemd unit file which should work, there are also extra directions for using systemd in the readme now too. I actually don't have a setup to test this on at the moment so if you could give it a test and let me know if it works that would be awesome.

**Comment by NeilBetham** [comment]
I'm going to close this for now. If you find that the systemd unit doesn't work please feel free to reopen this.
